prefix: |
  # awesome-fivem
  A curated list of FiveM resources
  ## Frameworks
  - [qb-core](https://github.com/qbcore-framework/qb-core)
  - [ESX](https://github.com/esx-framework/esx-legacy)
  - [NCS](https://github.com/NextCitizens/ncs_core)
  - [Atlas](https://github.com/AtlasFw/atl-core)
  ## Resources
minStars: 2
minStarsForFork: 3
excludeRepos:
  - .github
  - docs
  - website
users:
  - name: qbcore-framework
    excludeRepos:
      - breze_benefactor
  - name: iLLeniumStudios
    excludeRepos:
      - docs.illenium.dev
  - name: Constant-Development
  - name: GhzGarage
  - name: Disabled-Coding
  - name: ItsANoBrainer
    excludeRepos:
      - AdventOfCode
  - name: FjamZoo
  - name: NaorNC
  - name: IdrisDose
    excludeRepos:
      - wos_hombre_holocrons
      - Universal-LPC-Spritesheet-Character-Generator
  - name: Project-Sloth
  - name: loljoshie
  - name: project-codex
  - name: 5m1Ly
  - name: RodericAguilar
  - name: hoangducdt
  - name: vCodeScripts
  - name: Brichka-Dv
  - name: MrAladin-afs
    excludeRepos:
      - afs-discord-mod-bot
  - name: swkeep
  - name: Nerfednijt
  - name: Blumlaut
    excludeRepos:
      - ac-adu-dash
      - MTA
  - name: Holidayy95
  - name: Z3rio
  - name: IN1GHTM4R3
  - name: ImpulseFPS
  - name: Github-Samuel
  - name: OmiJod
  - name: trclassic92
  - name: JustDenali
  - name: overextended
    excludeRepos:
      - OxBot
  - name: itsHyper
  - name: llbooya
  - name: Bunny5578
  - name: Project-India
  - name: Doxy4
  - name: TheoLevi
  - name: buntyverma69
  - name: BubbleDudeAT
    excludeRepos:
      - v-town-website
  - name: wtftanveer
  - name: VORPCORE
  - name: tnj-development
  - name: xV1ncenTx
  - name: spyx444
  - name: DansMatee
  - name: cadburry6969
  - name: i-kulgu
  - name: renzuzu
  - name: doritohead
  - name: ic3d00
  - name: trickgodness
  - name: Skulrag
  - name: TitansProductions
  - name: oosayeroo
  - name: LifeGoal
  - name: rival-group
  - name: Prime-Script
  - name: randollocal
  - name: AxisGe0
  - name: MrEvilGamer
  - name: TonyCapon3
  - name: Kingsage311
  - name: stevn999
  - name: marcinhuu
  - name: Burn-One-Studios
  - name: Pluto-Really
  - name: McKleans-Scripts
  - name: VHall1
  - name: Kiminaze
  - name: OwenT1
  - name: Manliketjb
  - name: davidxd33
  - name: CrewDevelopement
  - name: jimathy
  - name: DvScriptsSK
  - name: KevinGirardx
  - name: KillerKei
  - name: MCS1999
  - name: LucidB1
  #- name: arabcodingteam
  - name: MonkeyWhisper
  - name: Lionh34rt
    excludeRepos:
      - QB-Cardealer
  - name: marcostom32
  - name: Mojito-Fivem
  - name: project-error
    excludeRepos:
      - projecterror.dev
  - name: Alivemonstor
  - name: devin-monro
  - name: jay-fivem
  - name: JoeSzymkowiczFiveM
  - name: JustLazzy
  - name: pushkart2
    excludeRepos:
      - caltech_101_transfer_learning
  - name: mirrox1337
  - name: ihyajb
  - name: BerkieBb
  - name: Project-Boosted
  - name: evanillaa
  - name: Developer-Bear
  - name: TasoOneAsia
  - name: izMystic
    excludeRepos:
      - harmonizedroleplay.com
      - darker-discord
  - name: Demo4889
  - name: Scullyy
  - name: YeahItsHayden
  - name: RoleplayRevisited
  - name: AtlasFw
  - name: TGRHavoc
  - name: SnailyCAD
    excludeRepos:
      - autoinstaller
      - autoupdater
  - name: Sub-Zero-Interactive
  - name: Sov-Nation
  - name: WolsG
  - name: NNakreSS
  - name: stolk88
  - name: xDreamLand
  - name: redutzu
  - name: LYCoreFramework
  - name: yamieboi
  - name: 0xDEMXN
  - name: Margaritoo
  - name: Ademo93
  - name: trainordevs
  - name: Kmack710
  - name: MrBerkk
  - name: AitLilCat-Script
  - name: Musiker15
  - name: HIJINX0
  - name: plasmaFPS
  - name: RebelScripts
  - name: Marttins011
  - name: Re1ease
  - name: RilloX01
  - name: MaDHouSe79
  - name: yxupy
  - name: titicarabina
  - name: Mackaelroni
  - name: ItsJustifY
  - name: Jakerssss
  - name: SamShanks1
  - name: Peple77
  - name: 17Swat09
  - name: CaseIRL
  - name: DonHulieo
  - name: RamiroDesigns
  - name: jaylac2000
    excludeRepos:
      - Quests
      - StaffStatus
  - name: JarvisFW
  - name: SneakyPanda998
  - name: Enzo-DC
  - name: zemBADEV
  - name: Leah-UK
  - name: BlackzoneV
  - name: nerohiro
  - name: esx-framework
    excludeRepos:
      - esx-documentation
      - esx-homepage
  - name: djjackYT
  - name: HunterSouvik
  - name: helenclarko
  - name: Smokey2022
  - name: aymannajim
  - name: PRS-Scripts
  - name: TazLTD
  - name: Crazy-tech458
  - name: NoobySloth
  - name: miquelmq20
  - name: Graz8
  - name: PA-Scripts
  - name: OfekAF
  - name: g3shaa
  - name: AgentofDeath
  - name: MrZainRP
  - name: Virus18sp
  - name: slvidu
  - name: SharkyFP
  - name: RadhwaneDZ
  - name: TzuyuDev
  - name: ItzCelyrian
  - name: Pavan576
  - name: Sna-aaa
  - name: MaxAbyss
  - name: kunaltak606
  - name: IDKFORCE
  - name: Re2team
  - name: awojnarek
  - name: bamablood94
  - name: QuakeAcid
  - name: tom-osborne
  - name: alp1x
  - name: MeetxDev
  - name: Zotactiks
  - name: kingofkingzcd
  - name: IngPleb
  - name: Zach488
  - name: FAXES
    excludeRepos:
      - easycompile
      - faxstore-themes
      - disbotapijs
  - name: ARSSANTO
  - name: CurlyLegend
  - name: iboss21
  - name: philipx2017
  - name: meidricsq
  - name: DevLanceGood
    excludeRepos:
      - altV-Police
  - name: FM-Dev-Macke
  - name: regalonefour
  - name: Wakie123213
  - name: Dragodast
  - name: BerlinDev-Five
  - name: n4n-0
  - name: thelindat
  - name: LukeWasTakenn
  - name: N-fire
  - name: realSixGrams
  - name: BombayV
  - name: xenfovn
    excludeRepos:
    - DDOS-SERVER
  - name: youngsinatra99
  - name: ygtdev
  - name: Equilibrium-Studio
  - name: WillFatty
  - name: Tex27
  - name: GENESEE5M
  - name: Griefa
  - name: NNCRP
  - name: carbontheape
  - name: TheHorizonDev
  - name: StuxxyOfficial
  - name: MayBacco
  - name: loaf-scripts
  - name: Predator7158
  - name: markthatsound
  - name: FaultyMatrix
  - name: JulyGee
  - name: Boom1053
  - name: WEEZOOKARP
  - name: Slimeemils
  - name: CritteRo
  - name: qy242
  - name: Spazd
  - name: reversum
  - name: VikingCat32
  - name: kingkongNutSack
  - name: DarkloaderTM
  - name: NImaism
  - name: czsquizer
  - name: AvarianKnight
  - name: ThymonA
    excludeRepos:
      - RedM-Positions
      - redm_extended
      - rdx_menu_dialog
  - name: JamesSc0tt
  - name: clementinise
  - name: Kaves47
  - name: Xogy
  - name: Alpha-Framework
  - name: EntityEvolution
    excludeRepos:
      - EntityEvolution.github.io
  - name: matetv
  - name: GlitchOo
  - name: ohbrime
  - name: zf-development
  - name: hhfw1
  - name: DOSE-420
  - name: infinitydevelopment14
  - name: Mahoneythebad
  - name: GucciFivem
  - name: Nathan-FiveM
  - name: BryanLTU
  - name: JL-Development
  - name: sgtherbz
  - name: Omega248
  - name: Andyyy7666
  - name: mmleczek
  - name: ExtremeGamingUK
  - name: idev-co
  - name: Renewed-Scripts
  - name: ansljeremy
  - name: Gubner
  - name: rcore-cz
  - name: SmokerIQ
  - name: xThrasherrr
  - name: TayMcKenzieNZ
  - name: jaimeadf
    excludeRepos:
      - BetterDiscordPlugins
      - discord-scraping
      - who-reacted
  - name: FlawwsX
  - name: Concept-Collective
  - name: ultrahacx
    excludeRepos:
      - discord_notebot
      - python_tools
      - twitterbot
      - AndroVNC-Origin
  - name: FuriousLeech
  - name: kel1x
  - name: Giana
    excludeRepos:
      - rat-bingo
      - sudoku
  - name: finalLy134
  - name: boostless
  - name: KamuiKody
  - name: spyx4
  - name: MonkeDevv
  - name: subhampro
  - name: NevoSwissa
  - name: zfbx
    excludeRepos:
    - Discord-Bot-Template
    - Yuno-v3
    - TorqueScript
    - Steam-Widget
  - name: Djpowell23
  - name: JonasDev99
  - name: hakos47
  - name: memojustone
  - name: Darr0k
  - name: NascentRP
  - name: JericoFX
  - name: ConnorTheDev
  - name: lucasmckillop
  - name: milotiro95
  - name: DanielCoelh0
  - name: menkzy
  - name: snipe-scripts
  - name: Wert22
  - name: ShomyTKD
  - name: creative2117
  - name: ItIsYeCat
  - name: Rav3n95
  - name: NarwakV
  - name: fetlito
  - name: IAmPerek
  - name: JnKTechStuff
  - name: jaxonfromkh
  - name: mikeyxb
  - name: AmirhosseinAghighi
  - name: kNickerzz
  - name: NightRider18133
  - name: sandralol
  - name: JZSandbox
  - name: Tomboru
  - name: d3st1nyh4x
    excludeRepos:
    - snek
    - Shrekmosphere
  - name: Rayzer567
  - name: Velkostatkar
  - name: KwalaGamer
  - name: mknzz
  - name: MrBeast2020
  - name: ActuallyStrez
  - name: djkenada
  - name: HunterHoch
  - name: CQC-Scripting
  - name: NylanderrDK
  - name: Kurosar
    excludeRepos:
    - LSL
  - name: amantu-qbit
  - name: sp1d3r1987
  - name: JiminyKroket
  - name: Newtonzz
  - name: GabbarFramework
  - name: LABNetwork1
  - name: 12LetterMeme
  - name: Gigavat02
  - name: Hiype
  - name: RaweRwe
  - name: Doxthehuman
  - name: sven20202020
  - name: iAlen17
  - name: illwhyrin
  - name: nagsterFVZ
  - name: iSheesho
  - name: skrimxyz
  - name: TheKingFyre
  - name: irsyadf27
  - name: SteffMet
  - name: Jaycc-Was-Taken
  - name: Slurpee100
  - name: Midsetts
  - name: maxxerr
  - name: belgamods
  - name: KrisKingo
  - name: Ekhion76
  - name: DIZZY-11
  - name: gallejens
  - name: Sudo442
  - name: ALFAMAS
  - name: LumioStudio
  - name: Revoxxi
  - name: MintKind
  - name: C0D3X3R0
  - name: shhada
  #- name: WolZephyr
  - name: WolfieValeo
  - name: Walfles
  - name: ApoloManCz
  - name: GeekHamza1
  - name: theManiKh
  - name: CxCore-xyz
  - name: TheCrypticOG
  - name: YASUOEK
  - name: xViperAG
  - name: DevX32
  - name: Liridon69
  - name: prefech
  - name: omar-othmann
    excludeRepos:
    - Pyqt5-MusicPlayers
    - PyQt5-splashScreen
    - PyQt5-YouTubeDownload
    - PythonVideoSpliter
    - PyQt5-Game
    - bklk
  - name: xFutte
  - name: RockySouthpaw
  - name: JaredScar
    includeRepos:
    - Badger-Antichewat
    - Badger_Discord_API
    - DiscordAcePerms
    - Bad-DiscordQueue
    - Multiverse-World-Manager
    - BadgerStaffPanel
    - DiscordDonatorPerks
    - PoliceEMSActivity
    - Bad-Discord
    - DiscordReports
    - BadgerStockMarket
    - DiscordChatRoles
    - ResourceEventScrambler
    - BadgerBankRobbery
    - BadgerTracer
    - DiscordWeaponPerms
    - Badssentials
    - DiscordTagIDs
    - DiscordVehicleRestrictions
  - name: wasabirobby
  - name: IAmElement
  - name: derens41210
  - name: antond15
  - name: NoNameMOD
  - name: Squibsie
  - name: zaphosting
    excludeRepos:
    - redem
  - name: james12007
  - name: TomGrobbe
    includeRepos:
    - vMenu
    - MenuAPI
  - name: HawkEye172
  #- name: CallMeDaddyBro
  #- name: dojwun
  - name: Dhruvpamnani
  - name: nepal4972
  - name: PuFGGs
  - name: Really-Pluto
